# Generated by Django 4.2.1 on 2024-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_scoreboard_score_alter_scoreboard_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoreboard",
            name="score",
        ),
        migrations.AddField(
            model_name="scoreboard",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
