# Generated by Django 4.2.1 on 2024-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_remove_scoreboard_score_scoreboard_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreboard",
            name="category",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
