# Generated by Django 4.2.1 on 2024-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_scoreboard_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreboard",
            name="level",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
